name:                statsd-rupp
version:             0.4.0.1
github:              "jprupp/statsd-rupp"
license:             BSD3
author:              "Jean-Pieerre Rupp"
maintainer:          "jprupp@protonmail.ch"
copyright:           "2023 Jean-Pierre Rupp"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            Simple StatsD Client
category:            System

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jprupp/statsd-rupp#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring >= 0.11.5.1 && < 2
- network >= 3.1.4.0 && < 4
- unliftio >= 0.2.25 && < 2
- unordered-containers >= 0.2.19.1 && < 2
- vector >= 0.13.0 && < 2

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

tests:
  statsd-rupp-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - statsd-rupp
    - hspec
    - QuickCheck
